name = "fund"
type = "javascript"

account_id = "8d06a01e958a084add5fcf155430e0fa"
workers_dev = true
route = ""
zone_id = ""
[durable_objects]
bindings = [
  { name = "PROJECTS", class_name = "DurableProjects" } 
]